use serde_json::Value;

#[test]
fn main_window_can_cancel_and_reopen_github_authorization() {
    // These artifacts are generated by the actual Tauri build, not a mocked invoke handler.
    let manifests: Value =
        serde_json::from_str(include_str!("../gen/schemas/acl-manifests.json")).unwrap();
    let capabilities: Value =
        serde_json::from_str(include_str!("../gen/schemas/capabilities.json")).unwrap();
    for command in ["cancel_github_connection", "reopen_github_authorization"] {
        let permission = format!("allow-{}", command.replace('_', "-"));
        assert_eq!(
            manifests["__app-acl__"]["permissions"][&permission]["commands"]["allow"],
            serde_json::json!([command]),
            "Tauri must generate permission for {command}"
        );
        let grants: Vec<_> = capabilities
            .as_object()
            .unwrap()
            .values()
            .filter(|capability| {
                capability["permissions"]
                    .as_array()
                    .unwrap()
                    .contains(&Value::String(permission.clone()))
            })
            .collect();
        assert!(!grants.is_empty(), "No window can invoke {command}");
        for grant in grants {
            assert_eq!(grant["windows"], serde_json::json!(["main"]));
            assert!(
                grant.get("remote").is_none(),
                "OAuth controls must remain local"
            );
        }
    }
}
