"""Check that every Tauri command handler is declared in build.rs's app manifest.

A command registered in main.rs's generate_handler! but missing from
AppManifest::commands has no autogenerated permission, so a clean checkout
fails capability validation even when a stale local build still passes.
"""
from pathlib import Path
import re
import sys

TAURI = Path(__file__).resolve().parent.parent / 'src-tauri'


def manifest_commands(build_rs):
    block = re.search(r'AppManifest::new\(\)\s*\.commands\(&\[(.*?)\]\)', build_rs, re.S)
    if not block:
        raise ValueError('build.rs has no AppManifest::new().commands(&[...]) list')
    return re.findall(r'"([A-Za-z0-9_]+)"', block.group(1))


def handler_commands(main_rs):
    block = re.search(r'generate_handler!\[(.*?)\]', main_rs, re.S)
    if not block:
        raise ValueError('main.rs has no tauri::generate_handler![...] list')
    body = re.sub(r'//[^\n]*', '', block.group(1))
    return [entry.strip().split('::')[-1] for entry in body.split(',') if entry.strip()]


def differences(build_rs, main_rs):
    manifest, handlers = manifest_commands(build_rs), handler_commands(main_rs)
    problems = []
    for label, names in (('build.rs', manifest), ('main.rs', handlers)):
        duplicates = sorted({name for name in names if names.count(name) > 1})
        if duplicates:
            problems.append(f'{label} lists commands more than once: {", ".join(duplicates)}')
    missing = sorted(set(handlers) - set(manifest))
    if missing:
        problems.append('Registered in main.rs but missing from build.rs: ' + ', '.join(missing))
    extra = sorted(set(manifest) - set(handlers))
    if extra:
        problems.append('Declared in build.rs but not registered in main.rs: ' + ', '.join(extra))
    return problems


def main():
    problems = differences((TAURI / 'build.rs').read_text(), (TAURI / 'src/main.rs').read_text())
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
